"""
Reinitialize ChromaDB with Sample Knowledge Base
Run this after database corruption or to reset the system
"""

import logging
from pathlib import Path
from embedding import TextEmbedder
from vector_db import VectorDatabase
import config

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def reinitialize_database():
    """Reinitialize ChromaDB with sample knowledge base"""
    
    print("=" * 80)
    print("  REINITIALIZING CHROMADB WITH SAMPLE KNOWLEDGE BASE")
    print("=" * 80)
    
    # Initialize components
    print("\n1. Initializing embedder...")
    embedder = TextEmbedder()
    
    print("2. Initializing vector database...")
    vector_db = VectorDatabase(embedding_model=config.EMBEDDING_MODEL)
    
    # Sample knowledge base documents
    print("\n3. Preparing sample documents...")
    
    application_docs = [
        """
        VoiceAssist Pro is an AI-powered product support assistant designed to help users
        access product documentation using voice or text-based queries.

        The system supports multilingual speech-to-text input, semantic document retrieval,
        and grounded response generation. VoiceAssist Pro does not generate answers from
        general AI knowledge or external sources.

        VoiceAssist Pro is commonly used in customer support environments, internal company
        helpdesks, and technical documentation platforms where accuracy, consistency, and
        traceability of information are critical.
        """,

        """
        Internet Usage Policy for VoiceAssist Pro

        VoiceAssist Pro does not use the internet to answer user questions.
        The system does not perform live web searches, access external websites,
        or retrieve information from third-party services.

        All answers generated by VoiceAssist Pro are based solely on the internal
        knowledge base that has been explicitly provided and maintained by administrators.

        If requested information is not available in the internal knowledge base,
        the assistant will clearly state that it cannot find the requested information.
        """,

        """
        Account Registration and Password Reset

        To use VoiceAssist Pro, users must register with a valid email address.
        After registration, a verification email is sent and must be confirmed
        before the account can be accessed.

        Password Reset Procedure:
        1. Open the VoiceAssist Pro login page.
        2. Click the "Forgot Password" link below the password field.
        3. Enter the email address associated with the account.
        4. Submit the request and wait for the password reset email.
        5. Open the email and click the password reset link.
        6. Create a new password with at least eight characters, including one
           uppercase letter, one number, and one special character.
        7. Save the new password and log in using the updated credentials.

        For security reasons, accounts are temporarily locked after five consecutive
        failed login attempts and are automatically unlocked after thirty minutes.
        If issues persist, users should contact product support.
        """,

        """
        Audio Input and Speech-to-Text Support

        VoiceAssist Pro allows users to submit queries using uploaded audio files
        or live microphone input.

        Supported audio formats include WAV, MP3, M4A, FLAC, and OGG.
        The recommended maximum audio length per request is five minutes.

        The system automatically detects the spoken language in the audio input.
        Users may optionally specify the language manually to improve transcription
        accuracy.

        For best results, audio recordings should be clear, free of background noise,
        and spoken at a normal pace. If transcription fails, users should verify that
        the audio file is not corrupted and that required audio dependencies such as
        FFmpeg are properly installed.
        """,

        """
        Answer Generation and Knowledge Base Behavior

        VoiceAssist Pro generates answers exclusively from documents stored in its
        internal knowledge base.

        When a user submits a query, the system retrieves the most relevant document
        sections using semantic similarity search and generates a response grounded
        in that retrieved information.

        If the requested information is not present in the knowledge base, the
        assistant will explicitly state that the information is not available.
        This behavior prevents hallucinated or misleading responses and ensures
        transparent and reliable support interactions.

        Administrators are responsible for keeping the knowledge base accurate
        and up to date by adding or modifying documentation as needed.
        """,

        """
        Troubleshooting and Performance Information

        Users may experience slower responses during the first application startup.
        This behavior is expected, as AI models may need to download and initialize
        during the initial run.

        Audio playback issues may occur if the text-to-speech engine fails to load.
        In such cases, VoiceAssist Pro automatically attempts a fallback speech
        synthesis method to continue providing audio output.

        If the assistant consistently fails to answer questions, users should verify
        that the knowledge base has been populated with relevant and current documents.
        An empty or outdated knowledge base will limit the system's ability to respond.
        """,

        """
        Support and Escalation Policy

        VoiceAssist Pro provides automated assistance but does not replace human
        support for critical issues such as billing, account recovery, or service
        outages.

        Users can contact the product support team through the official support
        email address or helpdesk portal. Standard support requests are typically
        answered within one business day.

        Issues that significantly impact business operations should be marked
        as high priority to ensure faster escalation and resolution.
        """
    ]

    application_metadata = [
        {"language": "en", "source": "product_overview", "topic": "overview", "type": "description"},
        {"language": "en", "source": "policy", "topic": "internet_usage", "type": "policy"},
        {"language": "en", "source": "account_support", "topic": "password_reset", "type": "procedure"},
        {"language": "en", "source": "audio_support", "topic": "speech_to_text", "type": "usage"},
        {"language": "en", "source": "knowledge_base", "topic": "rag_behavior", "type": "explanation"},
        {"language": "en", "source": "troubleshooting", "topic": "performance", "type": "support"},
        {"language": "en", "source": "support_policy", "topic": "escalation", "type": "policy"}
    ]
    
    print(f"   Prepared {len(application_docs)} documents")
    
    # Chunk and embed documents
    print("\n4. Chunking and embedding documents...")
    all_chunks = []
    all_embeddings = []
    all_metadata = []
    
    for i, doc in enumerate(application_docs):
        print(f"   Processing document {i+1}/{len(application_docs)}...")
        
        # Chunk document
        chunks = embedder.chunk_text(doc)
        
        # Embed chunks
        chunks_with_emb = embedder.embed_chunks(chunks)
        
        for chunk in chunks_with_emb:
            all_chunks.append(chunk["text"])
            all_embeddings.append(chunk["embedding"])
            
            chunk_metadata = application_metadata[i].copy()
            chunk_metadata["chunk_id"] = chunk["chunk_id"]
            chunk_metadata["original_doc_id"] = i
            all_metadata.append(chunk_metadata)
    
    print(f"   Created {len(all_chunks)} chunks")
    
    # Add to vector database
    print("\n5. Adding documents to vector database...")
    vector_db.add_documents(
        documents=all_chunks,
        embeddings=all_embeddings,
        metadatas=all_metadata
    )
    
    print(f"   ✓ Added {len(all_chunks)} chunks from {len(application_docs)} documents")
    
    # Verify database
    print("\n6. Verifying database...")
    test_query = "How do I reset my password?"
    query_embedding = embedder.embed_text(test_query)
    
    results = vector_db.query(
        query_embedding=query_embedding,
        n_results=3
    )
    
    print(f"   ✓ Database verification successful")
    print(f"   Retrieved {len(results['documents'])} documents for test query")
    
    print("\n" + "=" * 80)
    print("  DATABASE REINITIALIZATION COMPLETE ✅")
    print("=" * 80)
    print("\nYou can now run the application:")
    print("  streamlit run app.py")
    print()


if __name__ == "__main__":
    try:
        reinitialize_database()
    except Exception as e:
        logger.error(f"Reinitialization failed: {e}", exc_info=True)
        print(f"\n❌ ERROR: {e}")
        print("\nIf the error persists, try:")
        print("1. Delete the data/chroma_db folder manually")
        print("2. Run this script again")
